name: ARO network lab build
on:
  release:
    types: [published]
jobs:
  build-binaries-image-push:
    environment: Actions build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install depencencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install shc -y
      - name: Build binaries from script
        run: |
          mkdir lab_binaries
          bash shc_script_converter.sh
      - name: Login to Docker Hub
        run: echo -e "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker image - tagged
        run: docker build . -f Dockerfile -t amargherio/aro-flp-network:"${GITHUB_REF:10}"
      - name: Push tagged Docker image for release
        run: docker push amargherio/aro-flp-network:"${GITHUB_REF:10}"